import Head from 'next/head'
import styles from '../pages/_app.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="header">
          <div className="logo">
            <h1>
              CryptoNewbie
            </h1>
            <ul>
              <li>Accueil</li>
              <li>Contact Us</li>
              <li>Connexion</li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  )
}
